// =============================================================
// Mock data — Speech Intelligence Platform
// =============================================================

export const mockPoliticians = [
  { id: 'p1',  name: 'André Ventura',        party: 'CH',  photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p2',  name: 'Ana Catarina Mendes',  party: 'PS',  photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p3',  name: 'Paulo Rangel',         party: 'PSD', photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p4',  name: 'Mariana Mortágua',     party: 'BE',  photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p5',  name: 'Rui Rocha',            party: 'IL',  photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p6',  name: 'Rui Tavares',          party: 'L',   photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p7',  name: 'Paulo Raimundo',       party: 'PCP', photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p8',  name: 'Inês de Sousa Real',   party: 'PAN', photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p9',  name: 'Hugo Soares',          party: 'PSD', photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p10', name: 'Alexandra Leitão',     party: 'PS',  photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p11', name: 'Rita Matias',          party: 'CH',  photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p12', name: 'Bernardo Blanco',      party: 'IL',  photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p13', name: 'Pedro Rodrigues',      party: 'PS',  photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p14', name: 'José Moura Soeiro',    party: 'BE',  photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
  { id: 'p15', name: 'Duarte Marques',       party: 'PSD', photo_url: null, parlamento_url: 'https://www.parlamento.pt' },
]

export const mockSessions = [
  {
    id: 's1',
    date: '2024-11-20',
    title: 'Sessão Plenária — Debate Quinzenal com o PM',
    stream_url: 'https://canal.parlamento.pt/plenario',
    start_time: '2024-11-20T10:00:00Z',
    end_time: '2024-11-20T16:45:00Z',
    status: 'completed' as const,
    total_words: 28450,
    total_filler_words: 2634,
  },
  {
    id: 's2',
    date: '2024-11-19',
    title: 'Sessão Plenária — OE 2025 Discussão Especialidade',
    stream_url: 'https://canal.parlamento.pt/plenario',
    start_time: '2024-11-19T10:00:00Z',
    end_time: '2024-11-19T17:00:00Z',
    status: 'completed' as const,
    total_words: 31200,
    total_filler_words: 3408,
  },
  {
    id: 's3',
    date: '2024-11-26',
    title: 'Sessão Plenária — Debate de Urgência',
    stream_url: 'https://canal.parlamento.pt/plenario',
    start_time: '2024-11-26T10:00:00Z',
    end_time: null,
    status: 'active' as const,
    total_words: 4200,
    total_filler_words: 380,
  },
]

export const mockSpeeches = [
  {
    id: 'sp1',
    session_id: 's1',
    politician_id: 'p1',
    politician: mockPoliticians[0],
    started_at: '2024-11-20T10:08:00Z',
    ended_at: '2024-11-20T10:21:00Z',
    duration_seconds: 780,
    transcript: 'Sr. Presidente, quero deixar bem claro que este governo, portanto, está completamente falhado. Obviamente que nós, o Chega, temos sido os únicos, ou seja, a única força política que, de alguma forma, tem tentado, de certa forma, dar voz ao povo português. Portanto, o que estamos a ver é, basicamente, um executivo que não tem condições. Claramente que os portugueses já perceberam isto. Então, o que é que nós propomos? Pronto, é simples...',
    word_count: 312,
    filler_word_count: 48,
    filler_word_pct: 15.4,
    words_per_minute: 128,
    filler_occurrences: { 'portanto': 8, 'obviamente': 3, 'ou seja': 4, 'de alguma forma': 3, 'de certa forma': 4, 'basicamente': 2, 'claramente': 4, 'então': 6, 'pronto': 5, 'bom': 2, 'né': 7 },
  },
  {
    id: 'sp2',
    session_id: 's1',
    politician_id: 'p2',
    politician: mockPoliticians[1],
    started_at: '2024-11-20T10:22:00Z',
    ended_at: '2024-11-20T10:31:00Z',
    duration_seconds: 540,
    transcript: 'Sr. Presidente, senhoras e senhores deputados, o Partido Socialista apresentou propostas concretas para o Orçamento do Estado. Nós acreditamos que é possível fazer mais com os recursos existentes. A nossa proposta foca-se nas áreas da saúde, educação e habitação. Temos trabalhado com os parceiros sociais e com as autarquias para garantir que as medidas propostas respondem às necessidades reais dos portugueses.',
    word_count: 280,
    filler_word_count: 12,
    filler_word_pct: 4.3,
    words_per_minute: 156,
    filler_occurrences: { 'bom': 2, 'portanto': 3, 'então': 4, 'de facto': 3 },
  },
  {
    id: 'sp3',
    session_id: 's1',
    politician_id: 'p4',
    politician: mockPoliticians[3],
    started_at: '2024-11-20T11:05:00Z',
    ended_at: '2024-11-20T11:17:00Z',
    duration_seconds: 720,
    transcript: 'Sr. Presidente, o Bloco de Esquerda é, claramente, a força política que mais coerentemente tem defendido os trabalhadores neste país. Evidentemente, este orçamento não responde às necessidades das classes trabalhadoras. Concretamente, o que vemos é que o governo não tem propostas. No fundo, estamos perante uma opção política clara de proteger os mais ricos em detrimento dos mais pobres.',
    word_count: 298,
    filler_word_count: 22,
    filler_word_pct: 7.4,
    words_per_minute: 148,
    filler_occurrences: { 'claramente': 4, 'evidentemente': 3, 'concretamente': 3, 'no fundo': 4, 'portanto': 5, 'então': 3 },
  },
  {
    id: 'sp4',
    session_id: 's1',
    politician_id: 'p5',
    politician: mockPoliticians[4],
    started_at: '2024-11-20T11:45:00Z',
    ended_at: '2024-11-20T11:52:00Z',
    duration_seconds: 420,
    transcript: 'Sr. Presidente, a Iniciativa Liberal defende uma política fiscal baseada em dados e em evidência. Os impostos em Portugal são demasiado elevados. A solução não é gastar mais, é gastar melhor. Precisamos de reformas estruturais que aumentem a produtividade e a competitividade da nossa economia.',
    word_count: 190,
    filler_word_count: 5,
    filler_word_pct: 2.6,
    words_per_minute: 162,
    filler_occurrences: { 'portanto': 2, 'bom': 1, 'então': 2 },
  },
  {
    id: 'sp5',
    session_id: 's1',
    politician_id: 'p3',
    politician: mockPoliticians[2],
    started_at: '2024-11-20T13:00:00Z',
    ended_at: '2024-11-20T13:14:00Z',
    duration_seconds: 840,
    transcript: 'Sr. Presidente, o PSD tem, ao longo destes meses, portanto, contribuído de forma construtiva para o debate sobre o Orçamento. Obviamente, há divergências. Mas, pronto, o que é importante é que chegamos a um entendimento. Ora, o que eu quero dizer é que, bom, as propostas que foram apresentadas, de certa forma, vão ao encontro de algumas das nossas preocupações.',
    word_count: 340,
    filler_word_count: 28,
    filler_word_pct: 8.2,
    words_per_minute: 145,
    filler_occurrences: { 'portanto': 7, 'obviamente': 3, 'pronto': 4, 'ora': 3, 'bom': 4, 'de certa forma': 3, 'então': 4 },
  },
  {
    id: 'sp6',
    session_id: 's1',
    politician_id: 'p6',
    politician: mockPoliticians[5],
    started_at: '2024-11-20T14:00:00Z',
    ended_at: '2024-11-20T14:10:00Z',
    duration_seconds: 600,
    transcript: 'O Livre apresenta uma visão diferente para Portugal. Uma visão que coloca a sustentabilidade ambiental e a justiça social no centro da política económica. As nossas propostas são ambiciosas mas realistas. Acreditamos que Portugal pode ser um modelo de transição justa.',
    word_count: 210,
    filler_word_count: 6,
    filler_word_pct: 2.9,
    words_per_minute: 168,
    filler_occurrences: { 'portanto': 2, 'então': 3, 'bom': 1 },
  },
  {
    id: 'sp7',
    session_id: 's2',
    politician_id: 'p1',
    politician: mockPoliticians[0],
    started_at: '2024-11-19T10:15:00Z',
    ended_at: '2024-11-19T10:35:00Z',
    duration_seconds: 1200,
    transcript: 'Portanto, como eu já disse, e volto a dizer porque é importante, né, que os portugueses percebam que este governo, basicamente, não tem estratégia. Então, o que é que acontece? Obviamente que as famílias sofrem. Claramente que a economia está em dificuldades. De alguma forma, de certa forma, temos de encontrar alternativas. Portanto...',
    word_count: 425,
    filler_word_count: 74,
    filler_word_pct: 17.4,
    words_per_minute: 122,
    filler_occurrences: { 'portanto': 14, 'então': 9, 'obviamente': 6, 'claramente': 5, 'basicamente': 4, 'de alguma forma': 5, 'de certa forma': 4, 'né': 12, 'bom': 5, 'pronto': 7, 'ou seja': 3 },
  },
  {
    id: 'sp8',
    session_id: 's2',
    politician_id: 'p7',
    politician: mockPoliticians[6],
    started_at: '2024-11-19T11:00:00Z',
    ended_at: '2024-11-19T11:08:00Z',
    duration_seconds: 480,
    transcript: 'O Partido Comunista Português votará contra este Orçamento. As razões são claras: não responde às necessidades dos trabalhadores, não aumenta os salários de forma suficiente, não resolve o problema da habitação. A luta continua.',
    word_count: 175,
    filler_word_count: 4,
    filler_word_pct: 2.3,
    words_per_minute: 155,
    filler_occurrences: { 'portanto': 2, 'então': 2 },
  },
]

// Aggregate stats per politician across all speeches
export const mockPoliticianStats = mockPoliticians.map((p) => {
  const speeches = mockSpeeches.filter((s) => s.politician_id === p.id)
  const totalWords = speeches.reduce((sum, s) => sum + s.word_count, 0)
  const totalFiller = speeches.reduce((sum, s) => sum + s.filler_word_count, 0)
  const totalSeconds = speeches.reduce((sum, s) => sum + s.duration_seconds, 0)
  const avgWpm = speeches.length
    ? Math.round(speeches.reduce((sum, s) => sum + s.words_per_minute, 0) / speeches.length)
    : 0

  return {
    ...p,
    total_speeches: speeches.length,
    sessions_participated: new Set(speeches.map((s) => s.session_id)).size,
    total_words: totalWords,
    total_filler_words: totalFiller,
    overall_filler_pct: totalWords > 0 ? Math.round((totalFiller / totalWords) * 1000) / 10 : 0,
    total_seconds_speaking: totalSeconds,
    avg_words_per_minute: avgWpm,
    last_spoke_at: speeches.length ? speeches[speeches.length - 1].started_at : null,
  }
})

export const mockGlobalStats = {
  totalSessions: 34,
  totalSpeeches: 487,
  totalWords: 412800,
  totalFillerWords: 43650,
  overallFillerPct: 10.6,
  mostUsedFiller: 'portanto',
  mostUsedFillerCount: 3840,

  fillerByCategory: [
    { category: 'marcador',  count: 18200, pct: 41.7 },
    { category: 'vago',      count: 12400, pct: 28.4 },
    { category: 'óbvio',     count: 7800,  pct: 17.9 },
    { category: 'hesitação', count: 4850,  pct: 11.1 },
    { category: 'repetição', count: 400,   pct: 0.9 },
  ],

  top10FillerWords: [
    { word: 'portanto',        count: 3840, category: 'marcador' },
    { word: 'então',           count: 2960, category: 'marcador' },
    { word: 'obviamente',      count: 1820, category: 'óbvio' },
    { word: 'né',              count: 1640, category: 'hesitação' },
    { word: 'de certa forma',  count: 1520, category: 'vago' },
    { word: 'claramente',      count: 1440, category: 'óbvio' },
    { word: 'bom',             count: 1380, category: 'marcador' },
    { word: 'pronto',          count: 1210, category: 'marcador' },
    { word: 'basicamente',     count: 1090, category: 'vago' },
    { word: 'de alguma forma', count: 980,  category: 'vago' },
  ],

  fillerTrend: [
    { date: 'Out 1',  pct: 11.2 },
    { date: 'Out 8',  pct: 10.8 },
    { date: 'Out 15', pct: 12.1 },
    { date: 'Out 22', pct: 9.4 },
    { date: 'Out 29', pct: 10.3 },
    { date: 'Nov 5',  pct: 9.8 },
    { date: 'Nov 12', pct: 11.6 },
    { date: 'Nov 19', pct: 10.9 },
    { date: 'Nov 26', pct: 9.1 },
  ],

  fillerByParty: [
    { party: 'CH',  pct: 16.2, color: '#1B3A6B' },
    { party: 'PSD', pct: 9.4,  color: '#FF8C00' },
    { party: 'PS',  pct: 7.8,  color: '#FF69B4' },
    { party: 'BE',  pct: 8.1,  color: '#B22222' },
    { party: 'L',   pct: 5.2,  color: '#8B008B' },
    { party: 'IL',  pct: 4.8,  color: '#00BFFF' },
    { party: 'PAN', pct: 6.3,  color: '#228B22' },
    { party: 'PCP', pct: 3.9,  color: '#CC0000' },
  ],

  participationByParty: [
    { party: 'PS',  speeches: 148, minutes: 890,  color: '#FF69B4' },
    { party: 'PSD', speeches: 132, minutes: 794,  color: '#FF8C00' },
    { party: 'CH',  speeches: 98,  minutes: 648,  color: '#1B3A6B' },
    { party: 'IL',  speeches: 44,  minutes: 234,  color: '#00BFFF' },
    { party: 'BE',  speeches: 38,  minutes: 198,  color: '#B22222' },
    { party: 'L',   speeches: 14,  minutes: 82,   color: '#8B008B' },
    { party: 'PAN', speeches: 8,   minutes: 44,   color: '#228B22' },
    { party: 'PCP', speeches: 5,   minutes: 28,   color: '#CC0000' },
  ],

  speakingTimePerDay: [
    { day: 'Seg', minutes: 340 },
    { day: 'Ter', minutes: 390 },
    { day: 'Qua', minutes: 420 },
    { day: 'Qui', minutes: 360 },
    { day: 'Sex', minutes: 280 },
  ],
}

// Live session mock events
export const mockLiveEvents = [
  { id: 'e1', politician: mockPoliticians[0], text: 'Portanto, o que estamos a dizer é que este governo falhou completamente nas suas promessas eleitorais...', filler_words_found: ['portanto'], timestamp: new Date(Date.now() - 120000).toISOString() },
  { id: 'e2', politician: mockPoliticians[0], text: '...obviamente que os portugueses já perceberam isto, né? É que não há alternativa.', filler_words_found: ['obviamente', 'né'], timestamp: new Date(Date.now() - 90000).toISOString() },
  { id: 'e3', politician: mockPoliticians[1], text: 'O Partido Socialista tem trabalhado com responsabilidade para encontrar soluções concretas para os portugueses.', filler_words_found: [], timestamp: new Date(Date.now() - 60000).toISOString() },
  { id: 'e4', politician: mockPoliticians[1], text: 'De certa forma, as propostas que apresentámos vão ao encontro das necessidades dos cidadãos.', filler_words_found: ['de certa forma'], timestamp: new Date(Date.now() - 30000).toISOString() },
  { id: 'e5', politician: mockPoliticians[3], text: 'O Bloco de Esquerda defende que é necessário aumentar os salários de forma urgente e estrutural.', filler_words_found: [], timestamp: new Date(Date.now() - 10000).toISOString() },
]
