export const mockPoliticians = [
  { id: '1', name: 'Ana Catarina Mendes', party: 'PS', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 12 },
  { id: '2', name: 'Paulo Rangel', party: 'PSD', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 8 },
  { id: '3', name: 'André Ventura', party: 'CH', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 15 },
  { id: '4', name: 'Rui Rocha', party: 'IL', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 5 },
  { id: '5', name: 'Mariana Mortágua', party: 'BE', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 3 },
  { id: '6', name: 'Paulo Raimundo', party: 'PCP', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 2 },
  { id: '7', name: 'Inês de Sousa Real', party: 'PAN', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 4 },
  { id: '8', name: 'Rui Tavares', party: 'L', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 6 },
  { id: '9', name: 'Pedro Rodrigues', party: 'PS', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 9 },
  { id: '10', name: 'Hugo Soares', party: 'PSD', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 7 },
  { id: '11', name: 'Rita Matias', party: 'CH', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 11 },
  { id: '12', name: 'Bernardo Blanco', party: 'IL', photo_url: null, parlamento_url: 'https://www.parlamento.pt', created_at: '2024-01-01', times_caught: 4 },
]

export const mockDetections = [
  {
    id: '1',
    politician_id: '3',
    politician: mockPoliticians[2],
    timestamp: '2024-11-15T14:23:00Z',
    confidence_score: 0.97,
    video_clip_url: null,
    screenshot_url: null,
    tweeted: true,
    tweet_url: 'https://x.com',
    session_date: '2024-11-15',
    created_at: '2024-11-15T14:23:00Z',
  },
  {
    id: '2',
    politician_id: '1',
    politician: mockPoliticians[0],
    timestamp: '2024-11-15T11:45:00Z',
    confidence_score: 0.92,
    video_clip_url: null,
    screenshot_url: null,
    tweeted: true,
    tweet_url: 'https://x.com',
    session_date: '2024-11-15',
    created_at: '2024-11-15T11:45:00Z',
  },
  {
    id: '3',
    politician_id: '2',
    politician: mockPoliticians[1],
    timestamp: '2024-11-14T16:10:00Z',
    confidence_score: 0.88,
    video_clip_url: null,
    screenshot_url: null,
    tweeted: false,
    tweet_url: null,
    session_date: '2024-11-14',
    created_at: '2024-11-14T16:10:00Z',
  },
  {
    id: '4',
    politician_id: '11',
    politician: mockPoliticians[10],
    timestamp: '2024-11-14T10:30:00Z',
    confidence_score: 0.95,
    video_clip_url: null,
    screenshot_url: null,
    tweeted: true,
    tweet_url: 'https://x.com',
    session_date: '2024-11-14',
    created_at: '2024-11-14T10:30:00Z',
  },
  {
    id: '5',
    politician_id: '8',
    politician: mockPoliticians[7],
    timestamp: '2024-11-13T13:55:00Z',
    confidence_score: 0.91,
    video_clip_url: null,
    screenshot_url: null,
    tweeted: true,
    tweet_url: 'https://x.com',
    session_date: '2024-11-13',
    created_at: '2024-11-13T13:55:00Z',
  },
  {
    id: '6',
    politician_id: '9',
    politician: mockPoliticians[8],
    timestamp: '2024-11-13T15:22:00Z',
    confidence_score: 0.89,
    video_clip_url: null,
    screenshot_url: null,
    tweeted: false,
    tweet_url: null,
    session_date: '2024-11-13',
    created_at: '2024-11-13T15:22:00Z',
  },
]

export const mockStatsData = {
  detectionsOverTime: [
    { date: 'Out 1', count: 3 },
    { date: 'Out 8', count: 5 },
    { date: 'Out 15', count: 7 },
    { date: 'Out 22', count: 4 },
    { date: 'Out 29', count: 8 },
    { date: 'Nov 5', count: 6 },
    { date: 'Nov 12', count: 11 },
    { date: 'Nov 19', count: 9 },
    { date: 'Nov 26', count: 12 },
  ],
  detectionsByParty: [
    { party: 'CH', count: 28, color: '#1B3A6B' },
    { party: 'PS', count: 21, color: '#FF69B4' },
    { party: 'PSD', count: 15, color: '#FF8C00' },
    { party: 'L', count: 6, color: '#8B008B' },
    { party: 'IL', count: 9, color: '#00BFFF' },
    { party: 'BE', count: 3, color: '#B22222' },
    { party: 'PAN', count: 4, color: '#228B22' },
    { party: 'PCP', count: 2, color: '#CC0000' },
  ],
  detectionsByDayOfWeek: [
    { day: 'Seg', count: 18 },
    { day: 'Ter', count: 22 },
    { day: 'Qua', count: 25 },
    { day: 'Qui', count: 19 },
    { day: 'Sex', count: 14 },
  ],
  totalDetections: 87,
  totalSessions: 34,
  avgPerSession: 2.6,
}
